[lib]
name = "kernel.archs.x86_64"
requires = [
    "kernel.archs.x86_common",
    "kernel.mm.pmm",
    "libs.allocators",
    "libs.base64",
    "libs.elf",
    "libs.location",
    "libs.logging",
    "libs.result_option",
    "libs.traits",
    "vendor.limine",
]

[props]
include-path = "../interfaces/"
