[lib]
name = "kernel.archs.x86_64"
requires = [
    "kernel.libs.pmm",
    "libs.allocators",
    "libs.base64",
    "libs.elf",
    "libs.location",
    "libs.logging",
    "libs.result",
    "libs.traits",
    "vendor.limine",
]

[props]
include-path = "../common"
